const GRAPH_FILES = [
  "asama1_co2_per_capita_cv_scatter.png",
  "asama1_co2_per_capita_hata_bandi.png",
  "asama1_co2_per_capita_learning_curve.png",
  "asama1_co2_per_capita_zaman.png",
  "asama1_coal_co2_cv_scatter.png",
  "asama1_coal_co2_hata_bandi.png",
  "asama1_coal_co2_learning_curve.png",
  "asama1_coal_co2_zaman.png",
  "asama1_fossil_fuel_consumption_cv_scatter.png",
  "asama1_fossil_fuel_consumption_hata_bandi.png",
  "asama1_fossil_fuel_consumption_learning_curve.png",
  "asama1_fossil_fuel_consumption_zaman.png",
  "asama1_gas_co2_cv_scatter.png",
  "asama1_gas_co2_hata_bandi.png",
  "asama1_gas_co2_learning_curve.png",
  "asama1_gas_co2_shap.png",
  "asama1_gas_co2_zaman.png",
  "asama1_GDP_Growth_cv_scatter.png",
  "asama1_GDP_Growth_hata_bandi.png",
  "asama1_GDP_Growth_learning_curve.png",
  "asama1_GDP_Growth_shap.png",
  "asama1_GDP_Growth_zaman.png",
  "asama1_GDP_Per_Capita_cv_scatter.png",
  "asama1_GDP_Per_Capita_hata_bandi.png",
  "asama1_GDP_Per_Capita_learning_curve.png",
  "asama1_GDP_Per_Capita_zaman.png",
  "asama1_Industry_Value_Added_Pct_GDP_cv_scatter.png",
  "asama1_Industry_Value_Added_Pct_GDP_hata_bandi.png",
  "asama1_Industry_Value_Added_Pct_GDP_learning_curve.png",
  "asama1_Industry_Value_Added_Pct_GDP_shap.png",
  "asama1_Industry_Value_Added_Pct_GDP_zaman.png",
  "asama1_nuclear_consumption_cv_scatter.png",
  "asama1_nuclear_consumption_hata_bandi.png",
  "asama1_nuclear_consumption_learning_curve.png",
  "asama1_nuclear_consumption_zaman.png",
  "asama1_Population_cv_scatter.png",
  "asama1_Population_Density_cv_scatter.png",
  "asama1_Population_Density_hata_bandi.png",
  "asama1_Population_Density_learning_curve.png",
  "asama1_Population_Density_zaman.png",
  "asama1_Population_hata_bandi.png",
  "asama1_Population_learning_curve.png",
  "asama1_Population_zaman.png",
  "asama1_renewables_share_elec_cv_scatter.png",
  "asama1_renewables_share_elec_hata_bandi.png",
  "asama1_renewables_share_elec_learning_curve.png",
  "asama1_renewables_share_elec_shap.png",
  "asama1_renewables_share_elec_zaman.png",
  "asama1_temperature_change_from_ghg_cv_scatter.png",
  "asama1_temperature_change_from_ghg_hata_bandi.png",
  "asama1_temperature_change_from_ghg_learning_curve.png",
  "asama1_temperature_change_from_ghg_zaman.png",
  "asama1_Urbanization_Rate_cv_scatter.png",
  "asama1_Urbanization_Rate_hata_bandi.png",
  "asama1_Urbanization_Rate_learning_curve.png",
  "asama1_Urbanization_Rate_zaman.png",
  "asama2_forecast_karsilastirma.png",
  "asama2_LSTM_cv_scatter.png",
  "asama2_LSTM_cv.png",
  "asama2_LSTM_hata_bandi_test.png",
  "asama2_LSTM_hata_bandi_val.png",
  "asama2_LSTM_hata_bandi.png",
  "asama2_LSTM_learning_curve.png",
  "asama2_LSTM_residual_test.png",
  "asama2_LSTM_residual_val.png",
  "asama2_LSTM_residual.png",
  "asama2_RF_cv_scatter.png",
  "asama2_RF_cv.png",
  "asama2_RF_feature_importance.png",
  "asama2_RF_hata_bandi_test.png",
  "asama2_RF_hata_bandi_val.png",
  "asama2_RF_hata_bandi.png",
  "asama2_RF_learning_curve.png",
  "asama2_RF_residual_test.png",
  "asama2_RF_residual_val.png",
  "asama2_RF_residual.png",
  "asama2_RF_shap.png",
  "asama2_tum_modeller.png",
  "asama2_XGBoost_cv_scatter.png",
  "asama2_XGBoost_cv.png",
  "asama2_XGBoost_feature_importance.png",
  "asama2_XGBoost_hata_bandi_test.png",
  "asama2_XGBoost_hata_bandi_val.png",
  "asama2_XGBoost_hata_bandi.png",
  "asama2_XGBoost_learning_curve.png",
  "asama2_XGBoost_residual_test.png",
  "asama2_XGBoost_residual_val.png",
  "asama2_XGBoost_residual.png",
  "asama2_XGBoost_shap.png",
  "asama3_forecast_karsilastirma.png",
  "asama3_LSTM_cv_scatter.png",
  "asama3_LSTM_hata_bandi.png",
  "asama3_LSTM_residual.png",
  "asama3_RF_cv_scatter.png",
  "asama3_RF_feature_importance.png",
  "asama3_RF_hata_bandi.png",
  "asama3_RF_learning_curve.png",
  "asama3_RF_residual.png",
  "asama3_RF_shap.png",
  "asama3_tum_modeller.png",
  "asama3_XGBoost_cv_scatter.png",
  "asama3_XGBoost_feature_importance.png",
  "asama3_XGBoost_hata_bandi.png",
  "asama3_XGBoost_learning_curve.png",
  "asama3_XGBoost_residual.png",
  "asama3_XGBoost_shap.png",
] as const;

export type StagePrefix = "asama1" | "asama2" | "asama3";

export function getGraphsByStage(stage: StagePrefix): string[] {
  return GRAPH_FILES.filter((f) => f.startsWith(stage)).map(
    (f) => `/graphs/${f}`
  );
}

function humanizeFilename(filename: string): string {
  const base = filename.replace(/^.*\//, "").replace(/\.png$/, "");
  const withoutPrefix = base.replace(/^asama[123]_/, "");
  return withoutPrefix
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export { humanizeFilename };
